### ISSUE TITLE
can you give a complete version rosettascript for CUAMAb

### ISSUE THREAD

**Issue by JackYang825** [Fleishman-Lab/CUMAb#1]
In the paper "Any model that exhibited a Cα-carbonyl O RMSD greater than or equal to 0.5 Å in any of the CDRs was excluded from further consideration." I can not see the relative setting for that. can you give a complete version rosettascript for CUAMAb. Thanks

**Comment by atennenhouse** [comment]
Hi, sorry to be so slow to respond to this. We do this not in rosettascripts, but in a post-processing step in a python script. I added the script to the repo and added a step in the README describing how to use it. Hope this is helpful and lmk if anything doesn't make sense

**Comment by kmothera** [comment]
Hi I can't seem to find the "relax_command_line_example" or the "thread_command_example" example command lines specified in the README.

**Comment by atennenhouse** [comment]
Hi, these should be created in step 2.
